In [8]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\m_hossam\OneDrive\Desktop\data\google data\googleplaystore.csv")

In [12]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [13]:
df.shape[0]

10841

In [ ]:
df.shape[1]

13

In [37]:
idx = df.groupby('App')['Rating'].idxmax().dropna().astype(int)
df.loc[idx, ['App', 'Rating']]

                                                   App  Rating
8532                     +Download 4 Instagram Twitter     4.5
324                         - Free Comics - Comic Apps     3.5
4541                                                .R     4.5
4636                                            /u/app     4.7
5940                                            058.ba     4.4
...                                                ...     ...
6420                                       감성학원 BL 첫사랑     4.4
4362                                        💎 I'm rich     3.8
2575     💘 WhatsLov: Smileys of love, stickers and GIF     4.6
7559  📏 Smart Ruler ↔️ cm/inch measuring for homework!     4.0
882   🔥 Football Wallpapers 4K | Full HD Backgrounds 😍     4.7

[8197 rows x 2 columns]

In [38]:
df['Price'] = pd.to_numeric(df['Price'])

df[df['Type'] == 'Paid']['Price'].mean()

ValueError: Unable to parse string "$4.99" at position 234